{
 "title": "Alerting",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "daily backups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "systemd_units",
     "select": [
      [
       { "params": [ "active_code" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "daily_backup.service" }
     ]
    }
   ]
  },
  {
   "title": "Batteries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_device_friendlyName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_friendlyName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "nuc-srv1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Temperature - nuc-srv1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_host - cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp",
     "query": "SELECT mean(temp) as temp FROM \"temp\" WHERE $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "coretemp_packageid0_input" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "coretemp_package_id_0" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nuc-srv1" }
     ]
    },
    {
     "alias": "$tag_host - ssd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_device",
     "select": [
      [
       { "params": [ "temp_c" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk usage - root - nuc-srv1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "nuc-srv1" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage - data - nuc-srv1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "path",
       "operator": "=",
       "value": "/home/mathieu/services/iot/data/nextcloud"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory used percent - nuc-srv1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nuc-srv1" }
     ]
    }
   ]
  },
  {
   "title": "Http response times - nuc-srv1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Http probes - nuc-srv1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_server - $tag_status_code",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "status_code" ], "type": "tag" }
     ],
     "measurement": "http_response",
     "query": "SELECT count(\"http_response_code\") FROM \"http_response\" WHERE (http_response_code > 400) AND $timeFilter GROUP BY time($__interval), \"server\", \"status_code\" fill(0)",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "System load1 - nuc-srv1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nuc-srv1" }
     ]
    }
   ]
  },
  {
   "title": "docker stopped containers - nuc-srv1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nuc-srv1" }
     ]
    }
   ]
  },
  { "title": "pi-srv3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Temperature - pi-srv3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_host - cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp",
     "query": "SELECT mean(temp) as temp FROM \"temp\" WHERE $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pi-srv3" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage - root - pi-srv3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "pi-srv3" }
     ]
    }
   ]
  },
  {
   "title": "System load1 - pi-srv3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pi-srv3" }
     ]
    }
   ]
  },
  {
   "title": "Memory used percent - pi-srv3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pi-srv3" }
     ]
    }
   ]
  },
  {
   "title": "docker stopped containers - pi-srv3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pi-srv3" }
     ]
    }
   ]
  },
  { "title": "pi-bose", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Temperature - pi-bose",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_host - cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp",
     "query": "SELECT mean(temp) as temp FROM \"temp\" WHERE $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pi-bose" }
     ]
    }
   ]
  },
  {
   "title": "Disk usage - root - pi-bose",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "pi-bose" }
     ]
    }
   ]
  },
  {
   "title": "System load1 - pi-bose",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pi-bose" }
     ]
    }
   ]
  },
  {
   "title": "Memory used percent - pi-bose",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pi-bose" }
     ]
    }
   ]
  }
 ]
}