auth_enabled: false

server:
  log_level: warn
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    dir: /loki/data/wal

schema_config:
  configs:
    - from: 2024-12-05
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/data/chunks

  tsdb_shipper:
    active_index_directory: /loki/data/tsdb-index
    cache_location: /loki/data/tsdb-cache

limits_config:
  max_query_lookback: 1440h
  retention_period: 1440h

compactor:
  working_directory: /loki/data/retention
  delete_request_store: filesystem
  retention_enabled: true