{
 "title": "Performance",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "System load1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host - cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp",
     "query": "SELECT mean(temp) as temp  FROM \"temp\" WHERE $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "coretemp_packageid0_input" },
      { "condition": "OR", "key": "sensor", "operator": "=", "value": "cpu_thermal_input" }
     ]
    },
    {
     "alias": "$tag_host - ssd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_device",
     "select": [
      [
       { "params": [ "temp_c" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "traefik.service.request.duration",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service request count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "traefik.service.requests.total",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nextcloud usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpjson_nextcloud_stats",
     "select": [
      [
       {
        "params": [
         "ocs_data_nextcloud_storage_num_files"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "files" ], "type": "alias" }
      ],
      [
       { "params": [ "ocs_data_server_database_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "database_size" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "All partitions free space (GB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host - $tag_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"free\") FROM \"disk\" WHERE $timeFilter AND path !~ /\\/etc/ AND path !~ /\\/run/ and device != 'mapper/data' GROUP BY time($__interval), \"host\", \"fstype\", \"path\" fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "InfluxDB Shard bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_database",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "shard",
     "select": [
      [
       { "params": [ "diskBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "InfluxDB measurements",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_database",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "database",
     "select": [
      [
       { "params": [ "numMeasurements" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}