apiVersion: 1
deleteDatasources:
  - name: "InfluxDB-Internal"
    orgId: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://db_loki:3100
    password: ''
    user: ''
    database: ''
    jsonData:
      maxLines: 5000
  - name: InfluxDB-iot
    type: influxdb
    access: proxy
    url: http://db_influxdb:8086
    database: iot-db
    jsonData:
      httpHeaderName1: 'HeaderName'
      httpHeaderName2: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'HeaderValue'
      httpHeaderValue2: "Token $INFLUXDB_GRAFANA_TOKEN"
  - name: InfluxDB-monitoring
    type: influxdb
    access: proxy
    url: http://db_influxdb:8086
    database: monitoring-db
    jsonData:
      httpHeaderName1: 'HeaderName'
      httpHeaderName2: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'HeaderValue'
      httpHeaderValue2: "Token $INFLUXDB_GRAFANA_TOKEN"
